/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrganizerIndexRouteImport } from './routes/organizer.index'
import { Route as EventsIndexRouteImport } from './routes/events.index'
import { Route as OrganizerNewRouteImport } from './routes/organizer.new'
import { Route as EventsEventIdRouteImport } from './routes/events.$eventId'
import { Route as OrganizerEventIdEditRouteImport } from './routes/organizer.$eventId.edit'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizerIndexRoute = OrganizerIndexRouteImport.update({
  id: '/organizer/',
  path: '/organizer/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizerNewRoute = OrganizerNewRouteImport.update({
  id: '/organizer/new',
  path: '/organizer/new',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventIdRoute = EventsEventIdRouteImport.update({
  id: '/events/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizerEventIdEditRoute = OrganizerEventIdEditRouteImport.update({
  id: '/organizer/$eventId/edit',
  path: '/organizer/$eventId/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/organizer/new': typeof OrganizerNewRoute
  '/events/': typeof EventsIndexRoute
  '/organizer/': typeof OrganizerIndexRoute
  '/organizer/$eventId/edit': typeof OrganizerEventIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/organizer/new': typeof OrganizerNewRoute
  '/events': typeof EventsIndexRoute
  '/organizer': typeof OrganizerIndexRoute
  '/organizer/$eventId/edit': typeof OrganizerEventIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/organizer/new': typeof OrganizerNewRoute
  '/events/': typeof EventsIndexRoute
  '/organizer/': typeof OrganizerIndexRoute
  '/organizer/$eventId/edit': typeof OrganizerEventIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/signin'
    | '/signup'
    | '/events/$eventId'
    | '/organizer/new'
    | '/events/'
    | '/organizer/'
    | '/organizer/$eventId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/signin'
    | '/signup'
    | '/events/$eventId'
    | '/organizer/new'
    | '/events'
    | '/organizer'
    | '/organizer/$eventId/edit'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/signin'
    | '/signup'
    | '/events/$eventId'
    | '/organizer/new'
    | '/events/'
    | '/organizer/'
    | '/organizer/$eventId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  EventsEventIdRoute: typeof EventsEventIdRoute
  OrganizerNewRoute: typeof OrganizerNewRoute
  EventsIndexRoute: typeof EventsIndexRoute
  OrganizerIndexRoute: typeof OrganizerIndexRoute
  OrganizerEventIdEditRoute: typeof OrganizerEventIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizer/': {
      id: '/organizer/'
      path: '/organizer'
      fullPath: '/organizer/'
      preLoaderRoute: typeof OrganizerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizer/new': {
      id: '/organizer/new'
      path: '/organizer/new'
      fullPath: '/organizer/new'
      preLoaderRoute: typeof OrganizerNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId': {
      id: '/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof EventsEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizer/$eventId/edit': {
      id: '/organizer/$eventId/edit'
      path: '/organizer/$eventId/edit'
      fullPath: '/organizer/$eventId/edit'
      preLoaderRoute: typeof OrganizerEventIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  EventsEventIdRoute: EventsEventIdRoute,
  OrganizerNewRoute: OrganizerNewRoute,
  EventsIndexRoute: EventsIndexRoute,
  OrganizerIndexRoute: OrganizerIndexRoute,
  OrganizerEventIdEditRoute: OrganizerEventIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
